apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260521-234625-mw0qayls587t-service
spec:
  selector:
    app: enterprise-system-20260521-234625-mw0qayls587t
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
